import { TierConfiguration } from './types'

export const TIER_CONFIGURATIONS: TierConfiguration[] = [
  {
    tierId: 'classic',
    tierName: 'Classic',
    displayColor: '#6B7280',
    iconName: 'tier-classic',
    requirements: {
      minimumBalance: 2500,
      minimumAutopay: 1,
      autopayTypes: ['loan', 'bill'],
      creditCardAutopayLimit: 0,
      rollingBalancePeriodMonths: 3,
    },
    benefits: [
      {
        benefitId: 'apy-boost-classic',
        benefitName: 'APY Boost',
        benefitType: 'apy-boost',
        description: 'Earn extra interest on savings',
        icon: 'percentage-icon',
        tier: 'classic',
        apyBoostPercentage: 0.1,
      },
      {
        benefitId: 'fee-waiver-classic',
        benefitName: 'Fee Waiver',
        benefitType: 'fee-waiver',
        description: 'Waived ATM fees',
        icon: 'shield-icon',
        tier: 'classic',
        waivableFeesPerYear: 12,
        feeAmount: 2.5,
      },
    ],
    gracePeriodDays: 30,
    priority: 3,
  },
  {
    tierId: 'plus',
    tierName: 'Plus',
    displayColor: '#D4A574',
    iconName: 'tier-plus',
    requirements: {
      minimumBalance: 10000,
      minimumAutopay: 2,
      autopayTypes: ['loan', 'bill', 'credit-card'],
      creditCardAutopayLimit: 1,
      rollingBalancePeriodMonths: 3,
    },
    benefits: [
      {
        benefitId: 'apy-boost-plus',
        benefitName: 'APY Boost',
        benefitType: 'apy-boost',
        description: 'Earn higher interest on savings',
        icon: 'percentage-icon',
        tier: 'plus',
        apyBoostPercentage: 0.25,
      },
      {
        benefitId: 'fee-waiver-plus',
        benefitName: 'Fee Waiver',
        benefitType: 'fee-waiver',
        description: 'Waived transfer fees',
        icon: 'shield-icon',
        tier: 'plus',
        waivableFeesPerYear: 24,
        feeAmount: 2.5,
      },
      {
        benefitId: 'rewards-plus',
        benefitName: 'Third-Party Rewards',
        benefitType: 'third-party-rewards',
        description: 'Access to partner rewards',
        icon: 'gift-icon',
        tier: 'plus',
        partnerName: 'Rewards Partner XYZ',
        rewardRate: 0.001,
      },
    ],
    gracePeriodDays: 30,
    priority: 2,
  },
  {
    tierId: 'premium',
    tierName: 'Premium',
    displayColor: '#E8E8E8',
    iconName: 'tier-premium',
    requirements: {
      minimumBalance: 25000,
      minimumAutopay: 2,
      autopayTypes: ['loan', 'bill', 'credit-card'],
      creditCardAutopayLimit: 1,
      rollingBalancePeriodMonths: 3,
    },
    benefits: [
      {
        benefitId: 'apy-boost-premium',
        benefitName: 'APY Boost',
        benefitType: 'apy-boost',
        description: 'Earn best-in-class interest on savings',
        icon: 'percentage-icon',
        tier: 'premium',
        apyBoostPercentage: 0.5,
      },
      {
        benefitId: 'fee-waiver-premium',
        benefitName: 'Fee Waiver',
        benefitType: 'fee-waiver',
        description: 'Waived transfer and foreign ATM fees',
        icon: 'shield-icon',
        tier: 'premium',
        waivableFeesPerYear: 36,
        feeAmount: 2.5,
      },
      {
        benefitId: 'rewards-premium',
        benefitName: 'Premium Rewards',
        benefitType: 'third-party-rewards',
        description: 'Double rewards on partner purchases',
        icon: 'gift-icon',
        tier: 'premium',
        partnerName: 'Rewards Partner XYZ',
        rewardRate: 0.002,
      },
    ],
    gracePeriodDays: 30,
    priority: 1,
  },
]

export const FEATURE_FLAGS = {
  LOYALTY_HUB_ENABLED: true,
  RETROGRESSION_ALERTS_ENABLED: true,
  REAL_DOLLAR_BENEFITS_ENABLED: true,
  FAQ_SEARCH_ENABLED: true,
  PHASED_ROLLOUT_ENABLED: false,
  PHASE_2_PERCENTAGE: 0,
}

export const DESIGN_TOKENS = {
  colors: {
    tier: {
      classic: '#6B7280',
      plus: '#D4A574',
      premium: '#E8E8E8',
    },
    semantic: {
      success: '#10B981',
      warning: '#F59E0B',
      urgent: '#EF4444',
      neutral: '#F3F4F6',
    },
    text: {
      primary: '#111827',
      secondary: '#6B7280',
    },
  },
  spacing: {
    micro: '8px',
    sm: '12px',
    base: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  typography: {
    body: '16px',
    h1: '28px',
    h2: '24px',
    h3: '20px',
    small: '14px',
  },
  touchTarget: {
    minimum: '44px',
    recommended: '48px',
  },
}
